import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { browserIds, installedBrowsers } from "./browsers.js";
import { installManifest, readRegistration, runtimeDir, HOST_NAME } from "./native-host.js";
import { directoryHash, installSkills, skillSourceDirectory, skillTargets } from "./skills.js";
import { packageRoot, updateClientConfig, configPath } from "./config.js";
import { installClient } from "./install.js";
import { packageInfo } from "./version.js";
import { buildStatus } from "./source-fingerprint.js";

// A single install point that every surface points at, so "which version am I
// running?" is answered by the checkout that is on disk rather than by
// remembering which installer ran last. Nothing here is version-specific: the
// launchers resolve the runtime root at launch time, so the browser
// registration and every client config are written once and never again.
const RUNTIME_MANIFEST = "runtime.json";

export function manifestPath(dir = runtimeDir()) {
  return path.join(dir, RUNTIME_MANIFEST);
}

export function readRuntimeManifest(dir = runtimeDir()) {
  try {
    const parsed = JSON.parse(fs.readFileSync(manifestPath(dir), "utf8"));
    return typeof parsed?.root === "string" && parsed.root.length > 0 ? parsed : null;
  } catch {
    return null;
  }
}

export function writeRuntimeManifest(root, dir = runtimeDir()) {
  const manifest = { root: path.resolve(root), version: packageInfo().version ?? null, linkedAt: new Date().toISOString() };
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(manifestPath(dir), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return manifest;
}

function launcherHeader() {
  return [
    "#!/usr/bin/env node",
    "// Generated by `opencode-chromium link`. Resolves the runtime root at launch",
    "// time, so this path never changes when the checkout or branch does.",
    "import fs from \"node:fs\";",
    "import path from \"node:path\";",
    "import { createHash } from \"node:crypto\";",
    "import { fileURLToPath, pathToFileURL } from \"node:url\";",
    "",
    "const dir = path.dirname(fileURLToPath(import.meta.url));",
    `const activation = JSON.parse(fs.readFileSync(path.join(dir, ${JSON.stringify(RUNTIME_MANIFEST)}), "utf8"));`,
    "const root = activation.root;",
    "// Releases share the user's existing data. Isolation is an explicit developer opt-in.",
    "if (activation.stateIsolation === true && [\"development\", \"production\"].includes(activation.channel)) {",
    "  const state = path.join(dir, \"state\", activation.channel);",
    "  for (const [variable, folder] of Object.entries({ OPENCODE_BROWSER_MEMORY_DIR: \"memory\", AGENT_BROWSER_SEMANTIC_DIR: \"semantic\", AGENT_BROWSER_VISUAL_DIR: \"visual\", AGENT_BROWSER_PROVIDER_DIR: \"providers\", AGENT_BROWSER_ARTIFACT_DIR: \"artifacts\", AGENT_BROWSER_PROFILE_REGISTRY_DIR: \"profiles\" })) process.env[variable] ??= path.join(state, folder);",
    "}",
  ];
}

// A launcher must keep working on a branch that predates this module, so it
// cannot import the fingerprint helper from the checkout it resolves. This is a
// self-contained copy; tests/contracts/runtime-link.test.js fails if it ever
// disagrees with sourceFingerprint().
export const LAUNCHER_FINGERPRINT_SOURCE = [
  "function fingerprint(root) {",
  "  const hash = createHash(\"sha256\");",
  "  try { hash.update(\"package.json\").update(JSON.parse(fs.readFileSync(path.join(root, \"package.json\"), \"utf8\")).version ?? \"\"); } catch { /* no package.json */ }",
  "  const files = [];",
  "  const walk = (relative) => {",
  "    let entries;",
  "    try { entries = fs.readdirSync(path.join(root, relative), { withFileTypes: true }); } catch { return; }",
  "    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {",
  "      if (entry.name === \"node_modules\" || entry.name === \".git\") continue;",
  "      const child = `${relative}/${entry.name}`;",
  "      if (entry.isDirectory()) walk(child); else files.push(child);",
  "    }",
  "  };",
  "  walk(\"src\");",
  "  walk(\"native-host/src\");",
  "  walk(\"extension-src\");",
  "  walk(\"skills\");",
  "  walk(\"scripts\");",
  "  for (const file of [\"package.json\", \"bun.lock\", \"tsconfig.json\", \"tsconfig.backend.json\", \"wxt.config.ts\"]) { try { hash.update(file).update(fs.readFileSync(path.join(root, file))); } catch {} }",
  "  for (const relative of files.sort()) hash.update(relative).update(fs.readFileSync(path.join(root, relative)));",
  "  return hash.digest(\"hex\");",
  "}",
  "function newestSourceMtime(root) {",
  "  let newest = 0;",
  "  const walk = (relative) => {",
  "    let entries;",
  "    try { entries = fs.readdirSync(path.join(root, relative), { withFileTypes: true }); } catch { return; }",
  "    for (const entry of entries) {",
  "      const child = `${relative}/${entry.name}`;",
  "      if (entry.isDirectory()) walk(child);",
  "      else { try { newest = Math.max(newest, fs.statSync(path.join(root, child)).mtimeMs); } catch { /* raced */ } }",
  "    }",
  "  };",
  "  walk(\"src\");",
  "  walk(\"native-host/src\");",
  "  return newest;",
  "}",
].join("\n");

// An agent must never be served a bundle that no longer matches the tree, so
// the launcher rebuilds when stale. A bundle whose manifest predates the source
// hash (an older branch) is judged by time instead, and a broken tree still
// starts the last good bundle, loudly, rather than taking the tools down.
function launcherBuildGuard() {
  return [
    "",
    LAUNCHER_FINGERPRINT_SOURCE,
    "",
    "const manifestPath = path.join(root, \"dist\", \"build-manifest.json\");",
    "const entry = path.join(root, DIST_ENTRY);",
    "let built = null;",
    "try { built = JSON.parse(fs.readFileSync(manifestPath, \"utf8\")); } catch { /* never built */ }",
    "const stale = fs.existsSync(path.join(root, \"src\")) && (!built || (typeof built.sourceSha256 === \"string\"",
    "  ? built.sourceSha256 !== fingerprint(root)",
    "  : Date.parse(built.generatedAt ?? 0) < newestSourceMtime(root)));",
    "if (stale) {",
    "  const { spawnSync } = await import(\"node:child_process\");",
    "  const build = spawnSync(process.execPath, [path.join(root, \"scripts\", \"build.js\")], { stdio: [\"ignore\", \"ignore\", \"inherit\"] });",
    "  if (build.status !== 0) process.stderr.write(\"[opencode-browser-plugin] build failed; starting the last successful bundle\\n\");",
    "}",
    "if (!fs.existsSync(entry)) {",
    "  process.stderr.write(`[opencode-browser-plugin] no bundle at ${entry}; run: bun run build\\n`);",
    "  process.exit(1);",
    "}",
  ];
}

export function launcherSource(kind) {
  const lines = [...launcherHeader()];
  if (kind === "host") {
    // The host ships as source and runs directly, so a branch switch takes
    // effect on the next host start with no build step.
    lines.push("", "await import(pathToFileURL(path.join(root, \"native-host\", \"dist\", \"runtime.js\")).href);");
    return lines.join("\n") + "\n";
  }
  const entry = kind === "plugin" ? "dist/adapters/opencode/index.js" : "dist/adapters/mcp/server.js";
  lines.push(`const DIST_ENTRY = ${JSON.stringify(entry)};`, ...launcherBuildGuard(), "");
  if (kind === "plugin") {
    // OpenCode imports this module and reads the plugin exports, so they are
    // re-exported from whichever root is active.
    lines.push(
      "const mod = await import(pathToFileURL(entry).href);",
      "export default mod.default;",
      "export const opencodeBrowserPlugin = mod.opencodeBrowserPlugin;",
      "export const opencodeV2Plugin = mod.opencodeV2Plugin;",
      "export const opencodePluginModule = mod.opencodePluginModule;",
      "export const createOpenCodeSetup = mod.createOpenCodeSetup;",
    );
    return lines.join("\n") + "\n";
  }
  lines.push(
    "process.argv = [process.argv[0], entry, ...process.argv.slice(2)];",
    "await import(pathToFileURL(entry).href);",
  );
  return lines.join("\n") + "\n";
}

// `status` must answer "which version is live?" on any branch, including one
// that predates the status command, so it delegates to the active root when
// that root has it and otherwise reports what is knowable from here.
function statusSource() {
  return [
    "#!/usr/bin/env node",
    "// Generated by `opencode-chromium link`.",
    "import fs from \"node:fs\";",
    "import path from \"node:path\";",
    "import { fileURLToPath, pathToFileURL } from \"node:url\";",
    "",
    "const dir = path.dirname(fileURLToPath(import.meta.url));",
    `const manifest = JSON.parse(fs.readFileSync(path.join(dir, ${JSON.stringify(RUNTIME_MANIFEST)}), "utf8"));`,
    "const root = manifest.root;",
    "try {",
    "  const mod = await import(pathToFileURL(path.join(root, \"src\", \"cli\", \"runtime-link.js\")).href);",
    "  const { formatRuntimeStatus } = await import(pathToFileURL(path.join(root, \"src\", \"cli\", \"index.js\")).href);",
    "  process.stdout.write(`${formatRuntimeStatus(mod.runtimeStatus({ root }))}\\n`);",
    "} catch {",
    "  const { execFileSync } = await import(\"node:child_process\");",
    "  const git = (args) => { try { return execFileSync(\"git\", args, { cwd: root, encoding: \"utf8\", stdio: [\"ignore\", \"pipe\", \"ignore\"] }).trim(); } catch { return \"?\"; } };",
    "  let bundle = null;",
    "  try { bundle = JSON.parse(fs.readFileSync(path.join(root, \"dist\", \"build-manifest.json\"), \"utf8\")); } catch { /* not built */ }",
    "  process.stdout.write([",
    "    `runtime dir    ${dir}`,",
    "    `linked         ok  ${root}`,",
    "    `checkout       ${git([\"rev-parse\", \"--abbrev-ref\", \"HEAD\"])} @ ${git([\"rev-parse\", \"--short\", \"HEAD\"])} v${manifest.version ?? \"?\"}`,",
    "    `bundle         ${bundle ? `built ${bundle.generatedAt}` : \"missing\"}`,",
    "    \"note           this branch predates the status command; `git checkout dev` shows the full table\",",
    "  ].join(\"\\n\") + \"\\n\");",
    "}",
  ].join("\n") + "\n";
}

function writeExecutable(filePath, contents) {
  fs.writeFileSync(filePath, contents, "utf8");
  if (process.platform !== "win32") fs.chmodSync(filePath, 0o755);
  return filePath;
}

export function writeLaunchers(root, dir = runtimeDir()) {
  fs.mkdirSync(dir, { recursive: true });
  const launchers = {
    host: writeExecutable(path.join(dir, "host.mjs"), launcherSource("host")),
    mcp: writeExecutable(path.join(dir, "mcp.mjs"), launcherSource("mcp")),
    plugin: writeExecutable(path.join(dir, "plugin.mjs"), launcherSource("plugin")),
    status: writeExecutable(path.join(dir, "status.mjs"), statusSource()),
  };
  // The browser registration already points at this filename, so rewriting it
  // is enough: no registry or manifest change is needed on re-link.
  const wrapper = process.platform === "win32" ? path.join(dir, "opencode-browser-host.cmd") : path.join(dir, "opencode-browser-host");
  writeExecutable(wrapper, process.platform === "win32"
    ? `@echo off\r\n"${process.execPath}" "${launchers.host}"\r\n`
    : `#!/usr/bin/env sh\nexec "${process.execPath}" "${launchers.host}"\n`);
  return { ...launchers, wrapper, dir };
}

// Point every agent-facing surface at the launchers. Each config is rewritten
// in place from a backup, so re-linking is idempotent and reversible.
export function linkClientSurfaces({ dir = runtimeDir(), clients = ["codex", "opencode", "dsh"], dryRun = false } = {}) {
  const mcp = path.join(dir, "mcp.mjs");
  const plugin = path.join(dir, "plugin.mjs");
  const results = [];
  for (const client of clients) {
    if (client === "codex") {
      results.push({ client, ...installClient({ client: "codex", serverPath: mcp, dryRun }) });
      continue;
    }
    if (client === "opencode") {
      results.push({ client, ...installClient({ client: "opencode", pluginPath: plugin, dryRun }) });
      continue;
    }
    if (client === "dsh") {
      results.push(patchDshConfig(configPath("dsh"), mcp, dryRun));
      continue;
    }
    results.push({ client, skipped: true, reason: "unsupported surface" });
  }
  return { mcp, plugin, results };
}

// Legacy link shares the validated YAML planner used by setup/update.
export function patchDshConfig(filePath, target, dryRun = false) {
  if (!fs.existsSync(filePath)) return { client: "dsh", path: filePath, changed: false, reason: "not installed" };
  const result = updateClientConfig({ client: "dsh", filePath, serverPath: target, dryRun });
  return { client: "dsh", path: filePath, changed: result.changed, next: target, backup: result.backup };
}

function samePath(first, second) {
  if (typeof first !== "string" || typeof second !== "string") return false;
  return first.replaceAll("\\", "/").toLowerCase() === second.replaceAll("\\", "/").toLowerCase();
}

// Chromium resolves a native messaging host through several registry roots and
// stops at the first valid manifest. A browser that identifies itself as
// Chromium -- Brave in particular -- can therefore look in the shared Chrome
// root rather than its own, so a host registered only under the browser's own
// root can stay invisible and every connectNative fails as
// "Specified native messaging host not found". `chrome` is always a target for
// that reason: it costs one JSON file and one key when Chrome is absent, and it
// is the difference between working and not when it is the root actually read.
const SHARED_CHROMIUM_ROOTS = ["chrome"];

// Browsers to register: the ones present, the shared Chromium root, plus any
// already registered. Keeping an existing registration matters because a
// browser's executable can live somewhere we do not look, and never removing
// one keeps this from breaking a working setup.
export function linkTargets(dir = runtimeDir()) {
  const registered = browserIds().filter((browser) => readRegistration(browser, dir).registered);
  return [...new Set([...installedBrowsers(), ...SHARED_CHROMIUM_ROOTS, ...registered])];
}

export function linkRuntime({ root = packageRoot(), dir = runtimeDir(), dryRun = false, browsers = null } = {}) {
  const resolvedRoot = path.resolve(root);
  const targets = browsers ?? linkTargets(dir);
  if (dryRun) return { dryRun: true, root: resolvedRoot, dir, browsers: targets, manifest: manifestPath(dir), skills: skillTargets() };
  const launchers = writeLaunchers(resolvedRoot, dir);
  const manifest = writeRuntimeManifest(resolvedRoot, dir);
  const nativeHost = installManifest({
    auto: true,
    browsers: targets,
    extensionIds: [],
    hostPath: process.platform === "win32" ? launchers.wrapper : launchers.host,
  });
  const skills = installSkills({});
  return { root: resolvedRoot, dir, manifest, launchers, nativeHost, skills };
}

export function runtimeStatus({ root = packageRoot() } = {}) {
  const dir = runtimeDir();
  const manifest = readRuntimeManifest(dir);
  const resolvedRoot = path.resolve(root);
  const canonicalSkill = directoryHash(skillSourceDirectory()).sha256;
  const wrapper = path.join(dir, process.platform === "win32" ? "opencode-browser-host.cmd" : "opencode-browser-host");
  const installed = installedBrowsers();
  return {
    hostName: HOST_NAME,
    runtimeDir: dir,
    linked: Boolean(manifest) && samePath(manifest.root, resolvedRoot),
    manifest,
    root: resolvedRoot,
    version: packageInfo().version ?? null,
    branch: git(["rev-parse", "--abbrev-ref", "HEAD"], resolvedRoot),
    revision: git(["rev-parse", "--short", "HEAD"], resolvedRoot),
    dirty: (git(["status", "--porcelain"], resolvedRoot) ?? "") !== "",
    // Whether the browser will actually load us, not merely that a file exists.
    browserHost: { path: wrapper, installed: fs.existsSync(wrapper) },
    installedBrowsers: installed,
    registration: browserIds().map((browser) => ({ ...readRegistration(browser, dir), installed: installed.includes(browser) })),
    build: buildStatus(resolvedRoot),
    skills: skillTargets().map((target) => ({
      path: target,
      parity: fs.existsSync(path.join(target, "SKILL.md")) && directoryHash(target).sha256 === canonicalSkill,
    })),
    hosts: runningHosts(resolvedRoot),
  };
}

function git(args, cwd) {
  try {
    return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return null;
  }
}

// Best effort: when the OS will not let us enumerate processes we report null
// and the extension's own reconnect still picks up the new code. A host is
// short-lived by design -- the extension starts one on demand -- so finding
// none is normal rather than a fault.
function runningHosts(root = packageRoot()) {
  const needles = [
    path.join(root, "native-host", "src", "host.js"),
    path.join(runtimeDir(), "host.mjs"),
  ].map((candidate) => candidate.replaceAll("\\", "/").toLowerCase());
  try {
    const rows = process.platform === "win32"
      ? [].concat(JSON.parse(execFileSync("powershell", ["-NoProfile", "-Command", "Get-CimInstance Win32_Process -Filter \"Name='node.exe'\" | Select-Object ProcessId,CommandLine | ConvertTo-Json -Compress"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], windowsHide: true }) || "[]"))
      : execFileSync("ps", ["-eo", "pid=,args="], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] })
        .split("\n").map((line) => line.trim().match(/^(\d+)\s+(.*)$/)).filter(Boolean)
        .map((match) => ({ ProcessId: Number(match[1]), CommandLine: match[2] }));
    return rows
      .filter((row) => {
        const commandLine = String(row.CommandLine ?? "").replaceAll("\\", "/").toLowerCase();
        return needles.some((needle) => commandLine.includes(needle));
      })
      .map((row) => ({ pid: row.ProcessId }));
  } catch {
    return null;
  }
}

export function syncRuntime({ root = packageRoot(), quiet = false, ifLinked = false } = {}) {
  const resolvedRoot = path.resolve(root);
  // Git hooks call this with --if-linked so it stays inert on a checkout that
  // was never linked to a runtime, which keeps the hook harmless for everyone
  // else working in the repository.
  if (ifLinked) {
    const manifest = readRuntimeManifest();
    if (!manifest || !samePath(manifest.root, resolvedRoot)) return { root: resolvedRoot, skipped: "not linked" };
  }
  const before = buildStatus(resolvedRoot);
  let rebuilt = false;
  if (before.stale) {
    execFileSync(process.execPath, [path.join(resolvedRoot, "scripts", "build.js")], { stdio: quiet ? "ignore" : "inherit" });
    rebuilt = true;
  }
  const hosts = runningHosts(resolvedRoot);
  return { root: resolvedRoot, rebuilt, fresh: !buildStatus(resolvedRoot).stale, stoppedHosts: [], hostsSupported: hosts !== null,
    pendingReload: Boolean(hosts?.length), instruction: "Reconnect tools after active work finishes; sync never interrupts running hosts" };
}

export { runtimeDir };
